# NOTE: GPT told me to do these:
# tell tmux to use a 256-colour terminfo entry
# set -g default-terminal "tmux-256color"
# set -g mouse on
# set -g base-index 1
# setw -g pane-base-index 1



# NOTE: NeoVim told me to do these:
# - ⚠️ WARNING `focus-events` is not enabled. |'autoread'| may not work.
#   - ADVICE:
#     - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
#       set-option -g focus-events on
# - $TERM: tmux-256color
# - ⚠️ WARNING True color support could not be detected. |'termguicolors'| won't work properly.
#   - ADVICE:
#     - Add the following to your tmux configuration file, replacing XXX by the value of $TERM outside of tmux:
#       set-option -a terminal-features 'XXX:RGB'
#     - For older tmux versions use this instead:
#       set-option -a terminal-overrides 'XXX:Tc'


# Focus events support
set-option -g focus-events on
# True color settings
# set -g default-terminal "$TERM"
# set -ag terminal-overrides ",$TERM:Tc"
# # True colour support
set-option -a terminal-features 'xterm-256color:RGB'
# Mouse support
set -g mouse on
# start window numbers at 1 instead of 0
set -g base-index 1
# also start pane numbers at 1
setw -g pane-base-index 1
# set C-. as prefix
# unbind C-b
# set-option -g prefix C-.
# bind-key C-. send-prefix


# --- General ---
# set-option -g default-terminal "screen-256color" # Enable 256 colors

# --- STATUS BAR --- 
# Set the default status bar colors
# set-option -g status-style bg="#1793d1",fg=black

# Put status in the centre
# set-option -g status-justify centre

# set-option -g 

# NOTE: Colours are from colour 256 colour palette

# --- Status Bar ---
set-option -g status-position top # top or bottom
set-option -g status-justify centre # justify window list
set-option -g status-style bg=colour235,fg=colour248

# config options
# #[`colour`]`separator-char` #`Index`:#`WindowName` #[`colour`]`separator-char`

# Left side of status bar
set-option -g status-left '#[bg=colour238,fg=colour255] #S #[bg=colour235,fg=colour238]'
set-option -g status-left-length 30

# Right side of status bar
set-option -g status-right '#[bg=colour235,fg=colour238]#[bg=colour238,fg=colour255] %H:%M | %Y-%m-%d | %A#[bg=colour235,fg=colour238]'
# set-option -g status-right '#[bg=colour235,fg=colour238]#[bg=colour238,fg=colour255] %H:%M | %Y-%m-%d | %A'
set-option -g status-right-length 40


# Window list
set-window-option -g window-status-format '#[fg=colour248] #I:#W '

# #[`colour`]`separator-char` #`Index`:#`WindowName` #[`colour`]`separator-char`
set-window-option -g window-status-current-format '#[bg=colour235,fg=#1793d1]#[bg=#1793d1,fg=colour235] #I:#W #[bg=colour235,fg=#1793d1]'


# --- Panes ---
set-option -g pane-border-style fg=colour238
set-option -g pane-active-border-style fg=colour214

# --- Messages ---
set-option -g message-style bg=#1793d1,fg=colour235 #,bold





#### PLUGINS ####
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'alexwforsythe/tmux-which-key'
# WARNING: This does not actually show the key that should be used by default


# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'



# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
