# Tokyo Night theme
include tokyo-night-kitty.conf

# font setup


## zoom in with Ctrl+= or Ctrl+Plus
map ctrl+equal   change_font_size all +0.5
map ctrl+plus    change_font_size all +0.5

## zoom out with Ctrl+-
map ctrl+minus   change_font_size all -0.5



# TODO: Set up font change for neovim (FiraCode or smth else with ligaments)

# Give Kitty an 20%‐opaque background
# background_opacity 0.2
# (Optional) allow you to tweak it at runtime via shortcuts or remote control
dynamic_background_opacity yes


# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS