# preload=/home/peter/wallpapers/Snoopy Woodstock zonking in bed.jpg
# wallpaper = monitor,/home/peter/wallpapers/Snoopy Woodstock zonking in bed.jpg 

preload=/home/peter/wallpapers/snoopy_in_space.jpg
wallpaper = ,/home/peter/wallpapers/snoopy_in_space.jpg
# wallpaper = eDP-1,"/home/peter/wallpapers/Snoopy Woodstock zonking in bed.jpg"

