# Reflector configuration file for the systemd service.
#
# Empty lines and lines beginning with "#" are ignored.  All other lines should
# contain valid reflector command-line arguments. The lines are parsed with
# Python's shlex modules so standard shell syntax should work. All arguments are
# collected into a single argument list.
#
# See "reflector --help" for details.

# Recommended Options

# Set the output path where the mirrorlist will be saved (--save).

# Select the transfer protocol (--protocol).

# Select the country (--country).
# Consult the list of available countries with "reflector --list-countries" and
# select the countries nearest to you or the ones that you trust. For example:



# Use only the  most recently synchronized mirrors (--latest).

# Sort the mirrors by synchronization time (--sort).


-c AL -c AT -c BE -c BG -c HR -c CZ -c DK -c EE -c FI -c FR -c DE -c GR -c HU -c IT -c LV -c LT -c LU -c MD -c NL -c MK -c NO -c PL -c PT -c RO -c RS -c SK -c SI -c ES -c SE -c CH -c UA -c GB
--protocol https
--sort age
--latest 20
--download-timeout 20
--save /etc/pacman.d/mirrorlist

