TS_SEARCH_PATHS=(
  "$HOME/projects"
  "$HOME/projects/jobs"
  "$HOME/.config"
  "$HOME/dotfiles"
  "$HOME/dotfiles/home"
  "$HOME/dotfiles/home/.config"
  "$HOME"
)

TS_MAX_DEPTH=1

# TODO: Figure out how to set this
# TS_MIN_DEPTH=0
